# Generated by Django 5.1.2 on 2024-11-05 21:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('city', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CityWeather',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('temperature', models.IntegerField(blank=True, null=True, verbose_name='Температура в градусах цельсия')),
                ('pressure', models.IntegerField(blank=True, null=True, verbose_name='Атмосферное давление')),
                ('wind_speed', models.IntegerField(blank=True, null=True, verbose_name='Скорость ветра м/с')),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='city.city')),
            ],
            options={
                'verbose_name': 'Погода в городе',
                'verbose_name_plural': 'Погода в городах',
                'ordering': ('last_updated',),
            },
        ),
    ]
